/// Flutter icons ResMedia
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ResMedia
///      fonts:
///       - asset: fonts/ResMedia.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ResMedia {
  ResMedia._();

  static const _kFontFam = 'ResMedia';

  static const IconData sommelier = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData promo = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData chef = const IconData(0xe802, fontFamily: _kFontFam);
}
